services:
  app:
    build: ./app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "2"
          memory: 200M
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
