services:
  auth-db:
    image: postgres:16.3-alpine3.18
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: auth-db
      POSTGRES_HOST: auth-db
      POSTGRES_PORT: 5432
    command:
      - postgres
      - -c
      - shared_buffers=1GB
      - -c
      - effective_cache_size=4GB
      - -c
      - work_mem=128MB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - random_page_cost=1.1
      - -c
      - temp_file_limit=10GB
      - -c
      - log_min_duration_statement=200ms
      - -c
      - idle_in_transaction_session_timeout=10s
      - -c
      - lock_timeout=1s
      - -c
      - statement_timeout=60s
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.max=10000
      - -c
      - pg_stat_statements.track=all
    volumes: [auth:/var/lib/postgresql/data]
    healthcheck:
      test: [CMD-SHELL, pg_isready -U $POSTGRES_USER -d auth-db]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
  auth:
    build: ./auth
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: auth-db
      POSTGRES_HOST: auth-db
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_DEBUG: ""
    restart: always
    volumes: [auth_static:/app/static]
    depends_on:
      auth-db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html
      - ./data:/var/www/data
      - auth_static:/app/auth/static
    restart: always
    depends_on:
      - auth
  streaming-db:
    image: postgres:16.3-alpine3.18
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: streaming-db
      POSTGRES_HOST: streaming-db
      POSTGRES_PORT: 5432
    command:
      - postgres
      - -c
      - shared_buffers=1GB
      - -c
      - effective_cache_size=4GB
      - -c
      - work_mem=128MB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - random_page_cost=1.1
      - -c
      - temp_file_limit=10GB
      - -c
      - log_min_duration_statement=200ms
      - -c
      - idle_in_transaction_session_timeout=10s
      - -c
      - lock_timeout=1s
      - -c
      - statement_timeout=60s
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.max=10000
      - -c
      - pg_stat_statements.track=all
    volumes: [streaming:/var/lib/postgresql/data]
    healthcheck:
      test: [CMD-SHELL, pg_isready -U $POSTGRES_USER -d streaming-db]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
volumes:
  auth:
  auth_static:
  streaming:
