[release]
address = "0.0.0.0"
port = 8080
workers = 8
keep_alive = 5
log_level="normal"
limits = { forms = 32768 }

[debug]
address = "0.0.0.0"
port = 8080
workers = 8
keep_alive = 5
log_level = "debug"
limits = { forms = 32768 }
